#include "main.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"

#include "images/bookbackground.h"
#include "images/dungeon.h"
#include "images/juliet.h"
#include "images/poison.h"
#include "images/cathedral.h"
#include "images/deadjuliet.h"
#include "images/heart.h"

/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"

/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  START,
  PLAY,
  WIN,
  LOSE,
};

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;
  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial application state
  enum gba_state state = START;

  struct entity j = {100, 60, 0, 0};
  struct entity potion1 = {0, 0, 2, 1};
  struct entity potion2 = {220, 0, -1, 2};

  struct entity* entities[3] = {&j, &potion1, &potion2};

  int timer = 20;
  int tickCount = 60;
  char loseStr[] = "You Lost";
  char winStr[] = "You Win!";
  char startStr[] = "Press Start";

  int d = 1;

  // UNUSED(entities);
  // UNUSED(timer);
  // UNUSED(tickCount);

  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons

    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw

    waitForVBlank();
    
    if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)){
      main();
    }

    switch (state) {
      case START:
        if(d){
          drawFullScreenImageDMA(bookbackground);
          drawString(50, 40, startStr, BLACK);
          d=0;
        }

        
 
        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)){
          d=1;
          state = PLAY;
        }
        break;


      case PLAY:


        fillScreenDMA(GRAY);
        drawImageDMA(j.yPos, j.xPos, JULIET_WIDTH, JULIET_HEIGHT, juliet);

        char str[8];
        snprintf(str, 8, "%d", timer);
        drawString(10, 5, str, WHITE); 
        

        for (int i = 1; i < 3; i++){
          struct entity* e = entities[i];
          drawImageDMA(e->yPos, e->xPos, POISON_WIDTH, POISON_HEIGHT, poison);
        }

        for (int i = 1; i < 3; i++){
          struct entity* e = entities[i];
          if (e-> xPos < 0 || e->xPos > 220) e->xVel = -e->xVel;
          if (e-> yPos < 0 || e->yPos > 140) e->yVel = -e->yVel;
        }

        if (tickCount % 7 == 0){
          for (int i = 1; i < 3; i++){
            struct entity* e = entities[i]; 

            if (j.xPos < e->xPos + POISON_WIDTH &&
              j.xPos + JULIET_WIDTH > e->xPos &&
              j.yPos < e->yPos + POISON_HEIGHT &&
              j.yPos + JULIET_HEIGHT > e->yPos)
            {
              state = LOSE;
            }
          }
        }

        if (KEY_DOWN(BUTTON_UP, currentButtons)){
          j.yVel = -2;
        }
        if (KEY_DOWN(BUTTON_RIGHT, currentButtons)){
          j.xVel = 2;
        }
        if (KEY_DOWN(BUTTON_DOWN, currentButtons)){
          j.yVel = 2;
        }
        if (KEY_DOWN(BUTTON_LEFT, currentButtons)){
          j.xVel = -2;
        }


        if (j.xPos <= 0 && j.xVel < 0) j.xVel = 0;
        if (j.xPos >= 240-JULIET_WIDTH && j.xVel > 0) j.xVel = 0;
        if (j.yPos >= 160-JULIET_HEIGHT && j.yVel > 0) j.yVel = 0;
        if (j.yPos <= 0 && j.yVel < 0) j.yVel = 0;

        for (int i = 0; i < 3; i++){
            entities[i]->xPos += entities[i]->xVel;
            entities[i]->yPos += entities[i]->yVel;
        }

        if (tickCount == 0){
          timer--;
          tickCount = 60;
        }
        tickCount--;
        if(timer == 0) state = WIN;

        break;


      case WIN:
      
        waitForVBlank();
        if (d){
          drawFullScreenImageDMA(cathedral);
          d = 0;
        }
        drawString(50, 96, winStr, BLACK); 
        drawImageDMA(60, 100, HEART_WIDTH, HEART_HEIGHT, heart);
        break;

        
      case LOSE:
        waitForVBlank();
        if (d){
          drawFullScreenImageDMA(dungeon);
          d = 0;
        }
        drawString(10, 5, loseStr, WHITE); 
        drawImageDMA(60, 95, DEADJULIET_WIDTH, DEADJULIET_HEIGHT, deadjuliet);
        break;
    }

    previousButtons = currentButtons; // Store the current state of the buttons
  }

  UNUSED(previousButtons); // You can remove this once previousButtons is used

  return 0;
}
